/* -------------------------------------------------------------------------
Stack Overflow used for API handling 
---------------------------------------------------------------------------- */
/**
 * @class Movie
 * @extends MovieTitle
 * Represents a movie object with properties and methods for fetching details and random words.
 */
class Movie extends MovieTitle {
    /**
     * Creates an instance of Movie.
     * @param {string} title - The title of the movie.
     * @param {number} popularity - The popularity score of the movie.
     * @param {number} revenue - The revenue generated by the movie.
     */
    constructor(title, popularity, revenue) {
        super(popularity, revenue);
        this.title = title; // Movie title
        this.randomWord = 'Loading...'; // Placeholder for random word
        this.wordFetched = false; // Flag to check if random word is fetched
        this.genre = null; // Placeholder for movie genre
        this.releaseDate = null; // Placeholder for release date
    }

    /**
     * Fetches a random word from the Wordnik API.
     * @async
     * @returns {Promise<void>} Resolves when the word is successfully fetched.
     */
    async fetchRandomWord() {
        try {
            const response = await fetch(
                `https://api.wordnik.com/v4/words.json/randomWord?maxCorpusCount=-1&minDictionaryCount=1&maxDictionaryCount=-1&minLength=2&maxLength=-1&api_key=wnnjlmio6z6mx0os9gkq3o74im7ayv7j9t1a3lq2e2egygwct`
            ); // Fetches a random word
            const data = await response.json();
            this.randomWord = data.word; // Assigns the fetched random word
            this.wordFetched = true; 
        } catch (error) {
            console.error('Error fetching random word:', error);
            this.randomWord = 'Error'; // Sets error placeholder if fetch fails
            this.wordFetched = true; // Updates flag even if an error occurs
        }
    }

    /**
     * Fetches details of the movie, including genre and release date, using The Movie Database (TMDb) API.
     * @async
     * @returns {Promise<void>} Resolves when the movie details are successfully fetched.
     */
    async fetchDetails() {
        const apiKey = '75d20cb437df116a7b641bef86c09d20'; // TMDb API key
        const query = this.title; // Movie title for the query
        try {
            const response = await fetch(
                `https://api.themoviedb.org/3/search/movie?api_key=${apiKey}&query=${encodeURIComponent(query)}`
            ); // Fetches movie details using title
            const data = await response.json();
            const movieData = data.results[0]; 

            // Maps genre IDs to genre names
            const genreMap = {
                28: "Action",
                12: "Adventure",
                16: "Animation",
                35: "Comedy",
                80: "Crime",
                99: "Documentary",
                18: "Drama",
                10751: "Family",
                14: "Fantasy",
                36: "History",
                27: "Horror",
                10402: "Music",
                9648: "Mystery",
                10749: "Romance",
                878: "Science Fiction",
                10770: "TV Movie",
                53: "Thriller",
                10752: "War",
                37: "Western"
            };

            this.genre = genreMap[movieData.genre_ids[0]] || 'Unknown'; // Assigns genre 
            this.releaseDate = movieData.release_date || 'Unknown'; // Assigns release date
        } catch (error) {
            console.error('Error fetching movie details:', error);
            this.genre = 'Unknown'; // Defaults to 'Unknown' if fetch fails
            this.releaseDate = 'Unknown'; // Defaults to 'Unknown' if fetch fails
        }
    }

    /**
     * Handles displaying movie details and positioning the details container.
     * @async
     * @param {Event} event - The DOM event triggered by user interaction.
     * @returns {Promise<void>} Resolves after fetching and displaying movie details.
     */
    async handleDetails(event) {
        await this.fetchRandomWord(); // Fetches a random word
        await this.fetchDetails(); // Fetches movie details

        const detailsContainer = document.getElementById('details-container'); // Reference to the details container
        detailsContainer.classList.remove('loading'); // Removes loading state
        detailsContainer.innerHTML = `
            <h2>${this.title}</h2>
            <p><strong>Popularity:</strong> ${this.popularity}</p>
            <p><strong>Revenue:</strong> ${this.revenue}</p>
            <p><strong>Word Associated:</strong> ${this.randomWord}</p>
            <p><strong>Genre:</strong> ${this.genre}</p>
            <p><strong>Release Date:</strong> ${this.releaseDate}</p>
        `; // Updates the details container with fetched data

        const rect = event.target.getBoundingClientRect(); // Gets the target element's position
        detailsContainer.style.position = "absolute"; // Sets container position to absolute
        detailsContainer.style.top = `${rect.top + window.scrollY}px`; // Positions container vertically
        detailsContainer.style.left = `${rect.right + 10}px`; // Positions container horizontally
        detailsContainer.style.display = "block"; // Displays the details container
    }
}
